### PR TITLE
add sbt 1.0 test. fix IllegalArgumentException error

### PR DESCRIPTION
**Pull request by xuwei-k**
http://www.scala-sbt.org/1.x/docs/sbt-1.0-Release-Notes.html#sbt+1.0.0

> config("xyz") must be directly assigned to a capitalized val, like val Xyz = config("xyz"). This captures the lhs identifier into the configuration so we can use it from the shell later.

```
[error] Caused by: java.lang.IllegalArgumentException: requirement failed: id must be capitalized: nrConfig
[error] 	at scala.Predef$.require(Predef.scala:277)
[error] 	at sbt.librarymanagement.Configuration.<init>(Configuration.scala:19)
[error] 	at sbt.librarymanagement.Configuration$.of(Configuration.scala:72)
[error] 	at com.gilt.sbt.newrelic.NewRelic$.<init>(NewRelic.scala:51)
[error] 	at com.gilt.sbt.newrelic.NewRelic$.<clinit>(NewRelic.scala)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:27)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:31)
[error] 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:415)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
[error] 	at scala.collection.generic.Growable.loop$1(Growable.scala:54)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:58)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:186)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:44)
[error] 	at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:147)
[error] 	at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:143)
[error] 	at scala.collection.immutable.List.$plus$plus(List.scala:207)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:47)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1260)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1205)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1184)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1167)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:679)
[error] 	at sbt.internal.Load$.timed(Load.scala:1336)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:679)
[error] 	at sbt.internal.Load$.timed(Load.scala:1336)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:673)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:477)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:154)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:219)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:539)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:555)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:485)
[error] 	at sbt.internal.Load$.load(Load.scala:464)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:249)
[error] 	at sbt.internal.Load$.timed(Load.scala:1336)
[error] 	at sbt.internal.Load$.apply(Load.scala:249)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:65)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:695)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:695)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:687)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:125)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:228)
[error] 	at sbt.State$$anon$1.process(State.scala:234)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:23)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ExceptionInInitializerError
```

### CODE REVIEW

**Comment by tomjadams** [comment]
I'm seeing this error too, thanks for fixing it. There's a discussion here: https://github.com/sbt/librarymanagement/issues/134

**Comment by btd** [comment]
Ping @fiadliel @gilt can this be merged?

**Comment by Baccata** [comment]
Hello, I'm waiting for `sbt-newrelic` to support sbt 1.0.0 to make the jump myself. Any idea when this will get merged ? 

Thanks in advance !

**Comment by fiadliel** [comment]
Merged https://github.com/gilt/sbt-newrelic/pull/45 which fixes this. Thanks and sorry for the delay!

**Pull request closed without merging**
