### PR TITLE
Add support for setting error_collector.ignore_status_codes in newrelic.yml

### PR DESCRIPTION
**Pull request by epileptic-fish**
Hey guys, just ran into this use case and thought I'd open a PR. Does this look reasonable to you?

### CODE REVIEW

**Comment by fiadliel** [comment]
Yes, but can you update to minimise the diff for the config file please?

**Comment by epileptic-fish** [comment]
Sure!

**Comment by epileptic-fish** [comment]
@fiadliel thanks - I've removed the whitespace changes and removed an intellij file that I added by accident + updated the .gitignore to prevent that from happening again.

**Comment by fiadliel** [comment]
Thanks for the PR!

**Comment by epileptic-fish** [comment]
Brilliant thanks!

**Pull request merged**
