### PR TITLE
NewRelic browser support w/ playframework

### PR DESCRIPTION
**Pull request by Lykathia**
Playframework needs to be manually instrumented in order to work with New Relic's Browser monitoring. The auto_instrument flag in the browser_monitoring section must be set to false for this to work.

https://docs.newrelic.com/docs/agents/java-agent/instrumentation/page-load-timing-java

### CODE REVIEW

**Comment by fiadliel** [comment]
While I have very minor concerns about the change in behaviour here, I doubt any people are using this plugin with any kind of JSP service.

**Comment by Lykathia** [comment]
What behavior are you concerned about being changed? The default value maps back to how it was set previously (even tho the standard usecase would probably be to set it to false for most people using this plugin).

**Comment by fiadliel** [comment]
Oh I should have read it more closely. Yes, you're right, and this is completely safe.

Most people should set this to false, it's a pity it wasn't done before. Hopefully they'll read the documentation and figure it out :)

**Comment by fiadliel** [comment]
Thank you for your feedback and patch!

**Pull request merged**
