### PR TITLE
Bump NR version 3.26.1 -> 3.27.0

### PR DESCRIPTION
**Pull request by paololim**
New one just came out: https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-3270

### CODE REVIEW

**Comment by fiadliel** [comment]
Thanks for the PR!

**Comment by fiadliel** [comment]
The test "add-newrelic-api" is failing - would you mind updating to change the version number there too?

(I should probably refactor so one only needs to change this default value in a single place).

**Comment by paololim** [comment]
@fiadliel - Updated!

**Comment by fiadliel** [comment]
Thanks, merging :+1:

**Pull request merged**
