### PR TITLE
Upgrade NewRelic to 3.24.1

### PR DESCRIPTION
**Pull request by lloydmeta**
Upgrades to NewRelic agent 3.24.1

### CODE REVIEW

**Comment by fiadliel** [comment]
Thanks for the patch!

But I need to check if https://discuss.newrelic.com/t/java-agent-3-22-1-throws-npe-on-app-startup/31453 is fixed in this version; while enabling custom tracing avoided the bug, it's a nasty surprise for somebody who thinks a new NewRelic version can only be benign.

**Comment by lloydmeta** [comment]
@fiadliel wow ! didn't even know about this. Good idea on waiting to upgrade. Don't want to bring NPEs into Scala from Javaland if we can prevent it ;)

**Comment by lloydmeta** [comment]
@fiadliel 

I just upgraded the target to 3.24.1, which I think includes a fix in 3.24.0 that fixes the Netty NPE you mentioned (see [the changelog](https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes))

**Comment by lloydmeta** [comment]
@fiadliel I also went ahead and improved the Travis build fail because the build failed. It now no longer fails, uses the Travis docker infrastructure, and makes use of ivy caching. Overall things should be faster.

**Comment by fiadliel** [comment]
Thanks, looks great! And happy Christmas :)

**Pull request merged**
